trigger:
- backend/build-identity-background

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: cd backend/CRM && docker login -u softever -p softeverywhere docker.io && docker-compose -f docker-compose.yml build crmrevo-identity-background && docker-compose -f docker-compose.yml push crmrevo-identity-background
  displayName: 'deploy identity api'