trigger:
- backend/build-promotion-background

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: cd backend/CRM && docker login -u softever -p softeverywhere docker.io && docker-compose -f docker-compose.yml build crmrevo-promotion-background && docker-compose -f docker-compose.yml push crmrevo-promotion-background
  displayName: 'deploy promotion background'