trigger:
- backend/build-accounting-api

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: cd backend/CRM && docker login -u softever -p softeverywhere docker.io && docker-compose -f docker-compose.yml build crmrevo-accounting-api && docker-compose -f docker-compose.yml push crmrevo-accounting-api
  displayName: 'deploy accounting api'