trigger:
- backend/build-project-api

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: cd backend/CRM && docker login -u softever -p softeverywhere docker.io && docker-compose -f docker-compose.yml build crmrevo-project-api && docker-compose -f docker-compose.yml push crmrevo-project-api
  displayName: 'deploy project api'