trigger:
- backend/build-promotion-api

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: cd backend/CRM && docker login -u softever -p softeverywhere docker.io && docker-compose -f docker-compose.yml build crmrevo-promotion-api && docker-compose -f docker-compose.yml push crmrevo-promotion-api
  displayName: 'deploy promotion api'