version: '3.4'

services:
  crmrevo-core-api:
    image: crmrevo.azurecr.io/crmrevo-core-api:test
    build: 
      context: .
      dockerfile: src/Services/Core/Core.API/Dockerfile
    ports:
      - "5003:5003"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5003
  crmrevo-masterdata-api:
    image: crmrevo.azurecr.io/crmrevo-masterdata-api:test
    build: 
      context: .
      dockerfile: src/Services/MasterData/MasterData.API/Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5000
  crmrevo-project-api:
    image: crmrevo.azurecr.io/crmrevo-project-api:test
    build: 
      context: .
      dockerfile: src/Services/Project/Project.API/Dockerfile
    ports:
      - "5001:5001"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5001
  crmrevo-customer-api:
    image: crmrevo.azurecr.io/crmrevo-customer-api:test
    build: 
      context: .
      dockerfile: src/Services/Customer/Customer.API/Dockerfile
    ports:
      - "5002:5002"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5002
  crmrevo-promotion-api:
    image: docker.io/softever/crmrevo-promotion-api:latest
    build: 
      context: .
      dockerfile: src/Services/Promotion/Promotion.API/Dockerfile
    ports:
      - "5004:5004"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5004